import Head from 'next/head'
import Image from 'next/image'
import Footer from "./../../components/Footer";
import styles from '../../styles/Home.module.css'

const Parties = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kids Fun Parties</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Kids Fun Parties</h1>
        <p>Welcome to The Ski Deck&apos;s Kids Fun Parties website.</p>
      </main>
      <Footer />
    </div>
  );
};

export default Parties;
