import Head from "next/head";
import Image from "next/image";
import Link from "next/dist/client/link";
import styles from "./../styles/Home.module.css";
import { useRouter } from "next/dist/client/router";

export default function Home() {
  if (process.browser || typeof window !== "undefined") {
    console.log(window.location.protocol + `//` + window.location.host)
    if(window.location.host == "ski.co.za") {
      const router = useRouter();
      router.push(`TheSkiDeck`);
    } else if (window.location.host == "kidsfunparties.co.za") {
      const router = useRouter()
      router.push(`KidsFunParties`)
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>The Ski Deck Router</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{" "}
          <Link href="https://ski.co.za">
            <a>The Ski Deck</a>
          </Link>
        </h1>

        <div className={styles.grid}>
          <h3>How can we help you?</h3>
          <p>
            <Link href="/TheSkiDeck">
              <a>Ski Lessons</a>
            </Link>
          </p>
          <p>
            <Link href="/TheSkiDeck">
              <a>Ski Clothing</a>
            </Link>
          </p>
          <p>
            <Link href="/KidsFunParties">
              <a>Kids Fun Parties</a>
            </Link>
          </p>
          <p>
            <Link href="/KidsFunParties">
              <a>Family Fun</a>
            </Link>
          </p>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
