import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Shop = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{`Ski & Winter Sports Shop`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>{`Ski & Winter Sports Shop`}</h1>
        <p>Welcome to The Ski and Winter Sports Shop website.</p>
      </main>
    </div>
  );
};

export default Shop;
